services:
  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      SCHEMA: ${SCHEMA}
